POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvcmlzIiwiaWQiOiI2MmM2ZjQyNDM4NjBjZDNmOTBhYmI2NjEiLCJpYXQiOjE2NTcyMDU4MTl9.vXl9J4N3fvKci7tuQAqybNC8UMr17zHgBJFPVeIbXNc

{
    "title": "alrighty2",
    "author": "Matti traktorit2",
    "url": "www.matinTraktori.com",
    "likes": "232",
    "userId": "62c6f4243860cd3f90abb661"
}